commit_message: '[ci skip]'
files:
  - source: /Shared/data/MTA San Andreas/MTA/locale/en/*
    ignore_settings: 1
    ignore:
      - '*.psd'
    translation: /Shared/data/MTA San Andreas/MTA/locale/%two_letters_code%/%original_file_name%
    export_only_approved: true
  - source: /Shared/installer/locale/en.pot
    translation: /Shared/installer/locale/%two_letters_code%.%file_extension%
    export_only_approved: true
pull_request_labels:
  - 'localization'
