commit_message: '[ci skip]'
files:
  - source: /Shared/data/MTA San Andreas/MTA/locale/en_US/*
    ignore:
      - '*.psd'
    translation: /Shared/data/MTA San Andreas/MTA/locale/%locale_with_underscore%/%original_file_name%
    excluded_target_languages:
      - bs
      - fa
      - fil
      - he
      - hi
      - ka
      - ko
      - pt
      - srp
  - source: /Shared/installer/locale/en_US.pot
    translation: /Shared/installer/locale/%locale_with_underscore%.%file_extension%
pull_request_labels:
  - localization
