name: 'Stale draft PR handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  issues: read
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: multitheftauto/stale@releases/v4.1.0-mta-1.0.0
        id: stale
        with:
          stale-pr-message: 'This draft pull request is stale because it has been open for at least 90 days with no activity. Please continue on your draft pull request or it will be closed in 30 days automatically.'
          close-pr-message: 'This draft pull request was closed because it has been stalled for 30 days with no activity.'
          days-before-stale: 90
          days-before-close: 30
          only-pr-drafts: true
          stale-pr-label: 'stale'
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
